# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a368ad7e64df6b426ec77527a094c3ec57a941720f84fd0fe151d992cc50eacfe3df4a34dc54757322e2e8127ba956b4ea866654615497c36e757227c785b7cf

test:
  secret_key_base: cbed6febe87cfdbdeb5e8d1e1c491a9be76bd13592c1c9184532af670c5615a496f23d559568324b4395d2eba92982c569907163c92e62d50e86d3b14807c295

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
